export default function skills() {
    let skillsOptions = [
                     { value: "Java" , label:"Java" },
                     { value: "PHP", label: "PHP" },
                     { value: "Python", label: "Python" },
                     { value: "Java script", label: "Java script" },
                     { value: "Redmine" , label: "Redmine" },
                     { value: "GitHub Electron", label: "GitHub Electron" },
                     { value: "Git", label: "Git" },
                     { value: "Gulp.js", label: "Gulp.js" },
                     { value: "GitLab", label: "GitLab" },
                     { value: "GitHub", label: "GitHub" },
                     { value: "Android Studio", label: "Android Studio" },
                     { value: "Django", label: "Django" },
                     { value: "Apache Solr", label: "Apache Solr" },
                     { value: "Ansible", label: "Ansible" },
                     { value: "Play Framework", label: "Play Framework" },
                     { value: "Apache Ambari", label: "Apache Ambari" },
                     { value: "Spring Boot", label: "Spring Boot" },
                     { value: "Amazon Cloud Watch", label: "Amazon Cloud Watch" },
                     { value: "Apache NIFI", label: "Apache NIFI" },
                     { value: "PhantomJS", label: "PhantomJS" },
                     { value: "Kibana", label: "Kibana" },
                     { value: "Influx DB", label: "Influx DB" },
                     { value: "Grafana", label: "Grafana" },
                     { value: "Elk Stack", label: "Elk Stack" },
                     { value: "Elastic Search", label: "Elastic Search" },
                     { value: "Zabbix", label: "Zabbix" },
                     { value: "Mongo DB", label: "Mongo DB" },
                     { value: "Apache Solr", label: "Apache Solr" },
                     { value: "Jenkins", label: "Jenkins" },
                     { value: "Jenkins Continuous Integration", label: "Jenkins Continuous Integration" },
                     { value: "Oracle", label: "Oracle" },
                     { value: "Mysql", label: "Mysql" },
                     { value: "SQLAlchemy", label: "SQLAlchemy" },
                     { value: "Maria DB", label: "Maria DB" },
                     { value: "Redis", label: "Redis" },
                     { value: "Atlassian JIRA", label: "Atlassian JIRA" },
                     { value: "mSql", label: "mSql" },
                     { value: "Aqua Data studio", label: "Aqua Data studio" },
                     { value: "Postgres", label: "Postgres" },
                     { value: "RabbitMQ", label: "RabbitMQ" },
                     { value: "PgAdmin", label: "PgAdmin" },
                     { value: "MemCached", label: "MemCached" },
                     { value: "HSQlDB", label: "HSQlDB" },
                     { value: "WebLogic", label: "WebLogic" },
                     { value: "Tomcat", label: "Tomcat" },
                     { value: "Hibernate", label: "Hibernate" },
                     { value: "Junit Testing", label: "Junit Testing" },
                     { value: "Prototype.js", label: "Prototype.js" },
                     { value: "React Js", label: "React Js" },
                     { value: "Mockito", label: "Mockito" },
                     { value: "Spring", label: "Spring" },
                     { value: "Selenium RC", label: "Selenium RC" },
                     { value: "Apache Axis", label: "Apache Axis" },
                     { value: "Apache Spark", label: "Apache Spark" },
                     { value: "XML Gateway", label: "XML Gateway" },
                     { value: "XML Authoring", label: "XML Authoring" },
                     { value: "XML Database", label: "XML Database" },
                     { value: "HTML", label: "HTML" },
                     { value: "Redux", label: "Redux" },
                     { value: "Angular JS", label: "Angular JS" },
                     { value: "Underscore js", label: "Underscore js" },
                     { value: "CSS3", label: "CSS3" },
                     { value: "Bootstrap", label: "Bootstrap" },
                     { value: "Vue JS", label: "Vue JS" },
                     { value: "D3 JS", label: "D3 JS" },
                     { value: "Linux", label: "Linux" },
                     { value: "IOS", label: "IOS" },
                     { value: "Windows OS", label: "Windows OS" },
                     { value: "Chromebook OS", label: "Chromebook OS" },
                     { value: "Ruby on Rails", label: "Ruby on Rails" },
                     { value: "Agile Methodologies", label: "Agile Methodologies" },
                     { value: "C#", label: "C#" },
                     { value: "CLIST", label: "CLIST" },
                     { value: "Pascal", label: "Pascal" },
                     { value: "AutoIt", label: "AutoIt" },
                     { value: "Max", label: "Max" },
                     { value: "C++", label: "C++" },
                     { value: "C", label: "C" },
                     { value: "Fortran", label: "Fortran" },
                     { value: "PySpark", label: "PySpark" },
                     { value: "Sails.js", label: "Sails.js" },
                     { value: "Kotlin", label: "Kotlin" },
                     { value: "Redis Cache", label: "Redis Cache" },
                     { value: "kubernetes", label: "kubernetes" },
                     { value: "Docker", label: "Docker" },
                     { value: "Node JS", label: "Node JS" },
                     { value: "Perl", label: "Perl" },
                      { value: "C", label: "C" },

                 ];
    return {skillsOptions}
}